sudo: false
language: node_js
node_js:
  - "6"
  - "6.1"
cache:
  yarn: true
  directories:
    - bower_components
    - node_modules
branches:
  only:
    - master
install:
  - npm install -g npm@latest
  - npm install -g bower yarn
before_script:
  - yarn
  - bower install
  - npm prune
script:
  - npm run build
